service: alif-serverless-lambda-s3

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  stage: production
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: "*"

functions:
  processCSV:
    name: alif-processCSV
    handler: handler.processCSV
    events:
      - s3:
                  # CHANGE-TO-YOURNAME
          bucket: alif-serverless-bucket-input
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv
    environment:
      FIXED_WIDTH_BUCKET: ${self:resources.Resources.fixedwidth.Properties.BucketName}
      NODE_ENV: production

resources:
  Resources:
    fixedwidth:
      Type: AWS::S3::Bucket
      Properties:
                  # CHANGE-TO-YOURNAME
        BucketName: alif-serverless-bucket-output